### ISSUE TITLE
Generate Error - Invalid Class/Specialisation

### ISSUE THREAD

**Issue by S3R4N** [polonar16/RaidGroupGenerator#1]
![image](https://user-images.githubusercontent.com/105678414/192684705-b463333e-97ce-41a9-8b1d-1c909960257f.png)
[Raid Comp.xls](https://github.com/polonar16/RaidGroupGenerator/files/9661354/Raid.Comp.xls)

**Comment by polonar16** [comment]
'Marksman Hunter' should be listed as 'Marksmanship Hunter'

**Comment by polonar16** [comment]
'Marksman Hunter' should be listed as 'Marksmanship Hunter'
